# Generated by Django 5.1.6 on 2025-06-03 20:58

import django.db.models.deletion
import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, unique=True)),
                ('orig_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=shortener.models.default_expiry)),
            ],
        ),
        migrations.CreateModel(
            name='ClickStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shorturl')),
            ],
        ),
    ]
