# Generated by Django 5.1.6 on 2025-06-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_shorturl_short_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='link',
        ),
    ]
